plot_f_le_t: plot_f_le_t.cpp
	g++ plot_f_le_t.cpp -O3 -pthread -Wall -Wextra -std=c++23 -ffast-math -Wno-unused-parameter -Wno-unused-variable -o plot_f_le_t

plot_f_ge_t: plot_f_ge_t.cpp
	g++ plot_f_ge_t.cpp -O3 -pthread -Wall -Wextra -std=c++23 -ffast-math -Wno-unused-parameter -Wno-unused-variable -o plot_f_ge_t
